Feat: Implement no-duplicate-imports error rule
rslint/rslint pull request #107
Opened 2021-06-11 18:56 UTC by thecp

refs #53

2021-06-14 08:18 UTC, Stupremee requested changes

2021-06-14 08:18 UTC, Stupremee commented on crates/rslint_core/src/groups/errors/no_duplicate_imports.rs
> +    ```
Can you squash all of these codeblocks into a single one and write a comment "including exports"

2021-06-14 08:18 UTC, Stupremee commented on crates/rslint_parser/src/ast/stmt_ext.rs
> +pub trait Source {
I think it's better to add those methods on the structs instead of introducing a new trait.

2021-06-14 08:18 UTC, Stupremee commented
Two small nits. Otherwise looks really good! Thank you

2021-06-14 15:19 UTC, thecp commented
Thx @Stupremee all suggestions should be addressed

2021-06-15 14:46 UTC, Stupremee approved these changes

2021-06-15 15:32 UTC, Stupremee commented
Hmm. Seems like a rustdoc regression. I will investigate a bit. Temporarily, you can put `doc = false` into the `rslint-lsp` binary.

2021-06-15 16:15 UTC, merged